### ISSUE TITLE
Setting Days Inactive and Min Members both to 0 pulls only a few channels.

### ISSUE THREAD

**Issue by dougr-code** [Symantec/slack-autoarchive#47]
Even with both days inactive and min members set to 0 the script only seems to pull 8 out of 100s of channels. Wondering if it's a script issue or if I'm misunderstanding how it works. 

![Capture](https://user-images.githubusercontent.com/64867335/86981861-9f1e8f00-c13c-11ea-811e-297e010a4b54.PNG)

![Capture1](https://user-images.githubusercontent.com/64867335/86981873-a47bd980-c13c-11ea-8fd0-7da93f59b0f6.PNG)

**Comment by alexeiser** [comment]
... possibly because of paging? 
https://github.com/imduffy15/slack-autoarchive/commit/52ceb23360332d1f124210791f24ebfd45d06429

**Comment by dougr-code** [comment]
The merge you did actually did fix the issue I had. Thanks you. 

I have discovered something else, I'm not sure this is intended behavior or not. It looks like the bot is no longer added on dry run. This means that a proper dry run cannot be executed because it just says bot would be added to all channels. I had those 8 channels that had the bot added from earlier, they now show up as archived or not in a dry run based on the settings in config.py. However, the rest of the channels all just say "THIS IS A DRY RUN. BOT would have joined...." I have a feeling this won't affect the script actually running but it is a little scary not to be able to use the dry run.

Thanks again!

**Comment by alexeiser** [comment]
Depends on your thoughts of what dry run should do.... I personally wouldn’t have expected a dry run to cause messages to be added to every channel... so with the changes from Gareth... I decided to have dry run also not add or otherwise effect the environment. 

Down side - you have to run it with out dry run twice... first time will add the bot - second time would run archive. I thought about using a different flag- but it’s ugly no matter which way.

**Comment by dougr-code** [comment]
I completely agree with the message part. I didn't expect that either. The issue is the dry run doesn't even add the bot. It says BOT **would** have joined and doesn't actually add the bot to any channels.

**Comment by alexeiser** [comment]
I am not really following. 

1) you also were surprised that when DRYRUN=true that it added the bot to the channel and messages users. 
2) you don’t like that when DRYRUN=true that it lets you know which Chanels it would have joined - but doesn’t actual join them?
3) since the bot must be in a channel to access the history && post - it can’t check to see which channels would be archived until after it joins. 
4) if the bot joins a channel and doesn’t post - it’s almost Impossible to determine later if it should post (a work around where if the bot joined in the last 10minures - 24 hours... but it’s not a great long term model)


FWIW - it’s not a feature in this repo- so may be better to have this discussion in my fork.

**Comment by alexeiser** [comment]
FWIW -> I agree that its a bit scary but the updated code doesn't archive channels that it is "freshly" added too. So if you remove the bot from 8 channels.. run with out dryrun, and then run with dryrun it will tell you which channels it would archive. 

I am open to better ideas - the only other option I came up with is `DRY_RUN_ADD` and `DRY_RUN_ARCHIVE` as different flags. :/

**Comment by dougr-code** [comment]
Oh I see. I was hoping DRYRUN=true would add the bot to all channels and then just not post anything allowing a second run through to check which channels would be archived. I didn't realize the issue about not being able to tell whether it should post a second time around. The only post I would care about is the one for channels actually being archived. I was just going to remove the text from the templates.json anyway if it was going to post as I don't care if the bot actually says what it is. It shows up as channel_archiver based on the app I'm using to run it and that's plenty good. 

I recognize this is personal preference and others may wish for different behavior. I think the two flags is a good idea but I don't know how complicated that is to implement. The application is so simple to run that I don't think adding another flag would be a big deal from a user perspective. From a code complication perspective, I do not have the knowledge to speak to that.

Thanks for the tip on the freshly added piece.
